### ISSUE TITLE
Support esbuild 0.17+

### ISSUE THREAD

**Issue by handerss-tibco** [marvinhagemeister/karma-esbuild#54]
Esbuild has made a breaking API change which in turn breaks this library. In particular the `esbuild.build` method has been replaced by `esbuild.context` + a set of `watch`, `rebuild`, and `serve` etc, functions on the context object.

Trying to use esbuild 17 with this library causes the following error:

```
Invalid option in build() call: "incremental"
```

**Comment by karl-thomas** [comment]
Thanks! looking to upgrade to 0.17.x use some of the newer plugin stuff on a project, this would help us test it.
